Added the APIs using swagger
MusicConnectionMachine/RelationshipsG3 pull request #15
Opened 2017-03-17 04:12 UTC by ansjin

Added the swagger framework for adding the APIs.

2017-03-17 08:39 UTC, sacdallago commented
Why is swagger here and not [here](https://github.com/MusicConnectionMachine/api)?

2017-03-17 08:41 UTC, sacdallago commented
Also: there are conflicts before this can be merged, similar situation to [this](https://github.com/MusicConnectionMachine/StructuredData/pull/34#issuecomment-287297060)

2017-03-17 08:52 UTC, Henni commented
@sacdallago we run our relationship extraction algorithms inside separate containers. These support a simple API to receive sentences and afterwards return the relationships they extracted.

This has nothing to do with the database API and is only relevant for our own project.

2017-03-17 08:53 UTC, sacdallago commented
@Henni thanks for the clarification :)

2017-03-17 22:32 UTC, krishenk reviewed
Looks good, but make sure that you align the Dockerfile with the updated version of node, and clean up the extra empty lines.

2017-03-18 18:16 UTC, Henni requested changes
Except for the single comment looks good (even though I haven't worked with swagger yet)

2017-03-18 18:16 UTC, Henni commented on algorithms/ollie/api/swagger/swagger.yaml
> +      operationId: "getRelationshipsPOST"
This is nitpicking, but as this isn't a real REST call and more an RPC I suggest to not use the REST terminology and name this `extractRelationships`.

2017-03-18 20:23 UTC, ansjin commented on algorithms/ollie/api/swagger/swagger.yaml
> +      operationId: "getRelationshipsPOST"
yeah True, but actually swagger automatically add the GET and POST to the operations. But for our purpose I have renamed them

2017-03-18 21:13 UTC, Henni approved these changes

2017-03-18 22:48 UTC, merged