adding exemplar algorithm
MusicConnectionMachine/RelationshipsG3 pull request #24
Opened 2017-03-27 18:17 UTC by krishenk

Added exemplar algorithm for generating relationship triplets.

2017-03-27 20:37 UTC, kordianbruck commented on algorithms/exemplar/.swagger-codegen-ignore
> +#!docs/README.md
Do we need all this documentation here?

2017-03-27 20:37 UTC, kordianbruck commented on algorithms/exemplar/example/untitled
> +'use strict';
what is this file all about?

2017-03-27 20:37 UTC, kordianbruck commented on algorithms/exemplar/package.json
> +    "fs": "0.0.1-security"
Are you using yarn? If not, please lock down the versions.

2017-03-28 09:25 UTC, ansjin commented on algorithms/exemplar/controllers/extractRealtionshipsService.js
> +      instancesArr.push({quality:"", term1: list[0], term2:list[2], relation:list[1]});
As this algorithm does not give the quality, so that parameter can be removed only Instead of specifying it to Null.

2017-03-28 09:27 UTC, ansjin commented on algorithms/exemplar/docker-compose.yml
> +    - "3001:3001"
Please change the port number to something else. Maybe in future if we thought of running all the containers on the single machine then this port will conflict with the OpenIE port! So you can specify 3002

2017-03-28 09:32 UTC, ansjin requested changes

2017-03-28 09:32 UTC, ansjin commented on algorithms/exemplar/package.json
> +  "name": "openie-algorithm-relationshipg3-api",
change this to exemplar

2017-03-28 09:32 UTC, ansjin commented on algorithms/exemplar/scripts/deploy.sh
> +echo "Deploying the openie Algorithm in seprate container"
change it to exemplar and also the port here!

2017-03-28 13:24 UTC, Henni commented on algorithms/exemplar/package.json
> +    "fs": "0.0.1-security"
@krishenk have you done something about this, or do you need help with this?

2017-03-28 13:25 UTC, Henni commented
@ansjin could you redo your review on this?

2017-03-28 13:51 UTC, krishenk commented
@ansjin Please review.

2017-03-28 14:04 UTC, krishenk commented on algorithms/exemplar/package.json
> +    "fs": "0.0.1-security"
@Henni Yes please. How do I lock down the version?

2017-03-28 14:31 UTC, Henni commented on algorithms/exemplar/package.json
> +    "fs": "0.0.1-security"
running `npm shrinkwrap` creates a `npm-shrinkwrap.json` file which you have to check in.

Also this line (L20) looks wrong. `fs` is a module included in node.js and doesn't need to be in the package.json

2017-03-28 15:01 UTC, krishenk commented on algorithms/exemplar/package.json
> +    "fs": "0.0.1-security"
Alright, I will create the npm-shrinkwrap.json file and remove the fs module from package.json.

2017-03-28 15:11 UTC, krishenk commented
@Henni and @ansjin: All the requested changes have been made. Please review once again.

2017-03-28 19:08 UTC, ansjin approved these changes

2017-03-28 19:09 UTC, merged